### ISSUE TITLE
Update event for 3.1.11 and 3.2.1

### ISSUE THREAD

**Issue by 3D-I** [marttiphpbb/phpbb-ext-templateevents#8]
Hi Martti,
wondering if you are willing to update this useful tool to the latests.

Best regards. :)

**Comment by marttiphpbb** [comment]
It's updated now. Thanks for notifying.
Regards

**Comment by 3D-I** [comment]
Sorry but there are ...

**8** - ACP
**16** - ALL

3.1.11/3.2.1 got the same events, no differencies, you uploaded 10 events in total instead of 24 ?

https://wiki.phpbb.com/Release_Highlights/3.2.1#Template_Events
https://wiki.phpbb.com/Release_Highlights/3.2.1#ACP_Template_Events

**Comment by marttiphpbb** [comment]
All events are there, I've checked again one by one. But most of them were already there in 3.2.0 and got included in the one before last commit.
https://github.com/marttiphpbb/phpbb-ext-templateevents/commit/c3e62a3aeaead5904d4466e7a9b4e13011c86582
Maybe the listing of phpbb is not accurate.

**Comment by 3D-I** [comment]
That's what I thought, phpBB states since blah blah but doesn't provide a field for those updated since.
That's misleading somehow, sorry.

Thank you.

Regards.

- Marco

**Comment by Galixte** [comment]
Thanks for update 👍
